name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build App
    runs-on: ubuntu-latest

    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Build Application
        run: |
          mkdir -p dist
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o dist/nug-${{ matrix.goos }}-${{ matrix.goarch }}

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: nug-${{ matrix.goos }}-${{ matrix.goarch }}
          path: dist/nug-${{ matrix.goos }}-${{ matrix.goarch }}
